define(
    [
        './core',
        './views/AttributeTag',
        './views/CollectionView',
        './views/List',
        './views/Badge',
        './views/BasicNavbar',
        './views/Button',
        './views/Calendar',
        './views/Checkbox',
        './views/Container',
        './views/Context',
        './views/DropdownGroup',
        './views/Dropdown',
        './views/FileInput',
        './views/Glyph',
        './views/Grid',
        './views/Label',
        './views/Link',
        './views/Menu',
        './views/ModelView',
        './views/NavPills',
        './views/NavTabs',
        './views/OnOffGlyph',
        './views/Panel',
        './views/ProgressBar',
        './views/RadioGroup',
        './views/Select',
        './views/Span',
        './views/Table',
        './views/Tag',
        './views/TextArea',
        './views/TextField',
        './views/TimePicker',
        './views/DatePicker'
    ],
    function ($$)
    {
        return $$.views;
    }
);
